blank_issues_enabled: false
contact_links:
  - name: GDeveloppe Discord
    url: https://discord.gg/rjdYHvj
    about: Discuss on the forum or on the Discord to get help creating a game or identifying a bug.
  - name: GDeveloppe Forums
    url: https://forum.gdevelop-app.com
    about: You can also discuss game creation, new feature requests and bugs on the forum.
  - name: GDeveloppe Roadmap
    url: https://trello.com/b/qf0lM7k8/GDeveloppe-roadmap
    about: Look at the roadmap and vote on features that you want to see in GDeveloppe.
  - name: Submit a new game example that you created
    url: https://github.com/GDeveloppeApp/GDeveloppe-examples/issues/new/choose
    about: You can submit a game that you made to be added to examples in the "GDeveloppe-examples" repository 
  - name: Submit a new game extension that you created
    url: https://github.com/4ian/GDeveloppe-extensions/issues/new/choose
    about: You can submit an extension that you made in the "GDeveloppe-extensions" repository 
