// Automatically generated by GDevelop.js/scripts/generate-types.js
declare class gdWindowSettings {
  getClosable(): boolean;
  setClosable(newClosable: boolean): void;
  usingDefaultClosable(): boolean;
  revertToDefaultClosable(): void;
  delete(): void;
  ptr: number;
};