// Automatically generated by GDeveloppe.js/scripts/generate-types.js
declare class gdEventsContext {
  getReferencedObjectOrGroupNames(): gdSetString;
  getObjectNames(): gdSetString;
  getBehaviorNamesOfObjectOrGroup(objectOrGroupName: string): gdSetString;
  delete(): void;
  ptr: number;
};