// Automatically generated by GDeveloppe.js/scripts/generate-types.js
declare class gdEventsParametersLister {
  constructor(project: gdProject): void;
  getParametersAndTypes(): gdMapStringString;
  launch(events: gdEventsList): void;
  delete(): void;
  ptr: number;
};