// Automatically generated by GDeveloppe.js/scripts/generate-types.js
declare class gdExpressionCodeGenerationInformation {
  setFunctionName(functionName: string): gdExpressionCodeGenerationInformation;
  setStatic(): gdExpressionCodeGenerationInformation;
  setIncludeFile(includeFile: string): gdExpressionCodeGenerationInformation;
  addIncludeFile(includeFile: string): gdExpressionCodeGenerationInformation;
  delete(): void;
  ptr: number;
};