// Automatically generated by GDeveloppe.js/scripts/generate-types.js
declare class gdExtensionAndObjectMetadata {
  getExtension(): gdPlatformExtension;
  getMetadata(): gdObjectMetadata;
  delete(): void;
  ptr: number;
};