// Automatically generated by GDeveloppe.js/scripts/generate-types.js
declare class gdExpressionParserDiagnostic {
  isError(): boolean;
  getMessage(): string;
  getStartPosition(): number;
  getEndPosition(): number;
  delete(): void;
  ptr: number;
};