// Automatically generated by GDeveloppe.js/scripts/generate-types.js
declare class gdExpressionCompletionFinder {
  static getCompletionDescriptionsFor(node: gdExpressionNode, location: number): gdVectorExpressionCompletionDescription;
  getCompletionDescriptions(): gdVectorExpressionCompletionDescription;
  delete(): void;
  ptr: number;
};