// Automatically generated by GDeveloppe.js/scripts/generate-types.js
declare class gdExtensionAndExpressionMetadata {
  getExtension(): gdPlatformExtension;
  getMetadata(): gdExpressionMetadata;
  delete(): void;
  ptr: number;
};