// Automatically generated by GDeveloppe.js/scripts/generate-types.js
declare class gdExtensionAndBehaviorMetadata {
  getExtension(): gdPlatformExtension;
  getMetadata(): gdBehaviorMetadata;
  delete(): void;
  ptr: number;
};