// Automatically generated by GDeveloppe.js/scripts/generate-types.js
declare class gdInitialInstanceJSFunctor {
  constructor(): void;
  invoke(instance: gdInitialInstance): void;
  delete(): void;
  ptr: number;
};