// Automatically generated by GDeveloppe.js/scripts/generate-types.js
declare class gdMapStringExpressionMetadata {
  get(name: string): gdExpressionMetadata;
  set(name: string, prop: gdExpressionMetadata): void;
  has(name: string): boolean;
  keys(): gdVectorString;
  delete(): void;
  ptr: number;
};