// Automatically generated by GDeveloppe.js/scripts/generate-types.js
declare class gdNamedPropertyDescriptor extends gdPropertyDescriptor {
  constructor(): void;
  setName(name: string): gdPropertyDescriptor;
  getName(): string;
  delete(): void;
  ptr: number;
};