// Automatically generated by GDeveloppe.js/scripts/generate-types.js
declare class gdPairStringVariable {
  constructor(): void;
  getName(): string;
  getVariable(): gdVariable;
  delete(): void;
  ptr: number;
};