// Automatically generated by GDeveloppe.js/scripts/generate-types.js
declare class gdResourcesRenamer extends gdArbitraryResourceWorker {
  constructor(oldToNewNames: gdMapStringString): void;
  delete(): void;
  ptr: number;
};