// Automatically generated by GDeveloppe.js/scripts/generate-types.js
declare class gdUnfilledRequiredBehaviorPropertyProblem {
  getSourceProject(): gdProject;
  getSourceObject(): gdObject;
  getSourceBehaviorContent(): gdBehaviorContent;
  getSourcePropertyName(): string;
  getExpectedBehaviorTypeName(): string;
  delete(): void;
  ptr: number;
};