// Automatically generated by GDeveloppe.js/scripts/generate-types.js
declare class gdVectorPairStringTextFormatting {
  size(): number;
  getString(id: number): string;
  getTextFormatting(id: number): gdTextFormatting;
  delete(): void;
  ptr: number;
};