// Automatically generated by GDeveloppe.js/scripts/generate-types.js
declare class gdVectorExpressionParserDiagnostic {
  size(): number;
  at(index: number): gdExpressionParserDiagnostic;
  delete(): void;
  ptr: number;
};