// Automatically generated by GDeveloppe.js/scripts/generate-types.js
declare class gdVectorExpressionCompletionDescription {
  size(): number;
  at(index: number): gdExpressionCompletionDescription;
  delete(): void;
  ptr: number;
};