// This file is generated by make-version-metadata.js script
// Don't import this file directly, prefer to use newIDE/app/src/Version/index.js instead.
// prettier-ignore
module.exports = {
  "version": "5.3.198",
  "gitHash": "774bf0db6102cb644686fa7c754e496fad876d79",
  "versionWithHash": "5.3.198-774bf0db6102cb644686fa7c754e496fad876d79"
};
