// This file is generated by make-version-metadata.js script
// Don't import this file directly, prefer to use newIDE/app/src/Version/index.js instead.
// prettier-ignore
export default {
  "version": "5.3.198",
  "gitHash": "68f5398317433979babfb43e4f03e8d4b333b0d3",
  "versionWithHash": "5.3.198-68f5398317433979babfb43e4f03e8d4b333b0d3"
} as const;
