// This file is generated by make-version-metadata.js script
// Don't import this file directly, prefer to use newIDE/app/src/Version/index.js instead.
// prettier-ignore
export default {
  "version": "5.3.198",
  "gitHash": "4d81e88d2d4d299a94ca00d435db1dc44df0f47e",
  "versionWithHash": "5.3.198-4d81e88d2d4d299a94ca00d435db1dc44df0f47e"
} as const;
